### ISSUE TITLE
[Bug]: 打开软件后系统切换到夜间模式后软件崩溃

### ISSUE THREAD

**Issue by Qing-Novel** [15dd/wenku8reader#27]
### 检查单

- [X] 我已确认网络环境没有问题
- [X] 我已确认ip属地为中国大陆

### Bug描述

打开软件后系统切换到夜间模式后软件崩溃
错误代码：
java.lang.IllegalStateException: Fragment BookCaseFragment{50ce8d2} (9f8c180d-376f-4534-8772-6d4e79e5d0dd) did not return a View from onCreateView() or this was called before onCreateView().
	at androidx.fragment.app.Fragment.requireView(Fragment.java:2063)
	at com.cyh128.wenku8reader.fragment.BookCaseFragment.changeLayout(BookCaseFragment.kt:68)
	at com.cyh128.wenku8reader.fragment.BookCaseFragment.access$changeLayout(BookCaseFragment.kt:23)
	at com.cyh128.wenku8reader.fragment.BookCaseFragment$setBookcase.firstLaunchHandler$lambda$1(BookCaseFragment.kt:104)
	at com.cyh128.wenku8reader.fragment.BookCaseFragment$setBookcase.$r8$lambda$cAULMGbdaOX430Sc-z4sjfT9PjA(Unknown Source:0)
	at com.cyh128.wenku8reader.fragment.BookCaseFragment$setBookcase$$ExternalSyntheticLambda0.handleMessage(D8$$SyntheticClass:0)
	at android.os.Handler.dispatchMessage(Handler.java:113)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.loopProcess(ActivityThread.java:9998)
	at android.app.ActivityThread.main(ActivityThread.java:9987)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

### 安卓版本

aosp12

### 轻小说文库版本

v2.3.3

**Comment by 15dd** [comment]
等下个大版本更新

**Comment by Qing-Novel** [comment]
> 等下个大版本更新

好的大佬
