### ISSUE TITLE
新版本登陆即崩溃

### ISSUE THREAD

**Issue by zxbiao** [15dd/wenku8reader#31]
输入完帐号密码点登陆这崩溃了
`Build version: 3.0.0 
Build date: 1981-01-01 01:01:02 
Current date: 2024-10-02 14:39:26 
Device: Tianyi TYH641M 
 
Stack trace:  
java.lang.RuntimeException
	at com.cyh128.hikarinovel.data.repository.Wenku8Repository.getBookshelf-IoAF18A(Wenku8Repository.kt:229)
	at com.cyh128.hikarinovel.ui.view.splash.LoginViewModel.refreshBookshelfList(LoginViewModel.kt:64)
	at com.cyh128.hikarinovel.ui.view.splash.LoginActivity$onCreate$2$1.emit(LoginActivity.kt:51)
	at com.cyh128.hikarinovel.ui.view.splash.LoginActivity$onCreate$2$1.emit(LoginActivity.kt:48)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:397)
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.loopProcess(ActivityThread.java:9998)
	at android.app.ActivityThread.main(ActivityThread.java:9987)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cba98cc, Dispatchers.Main]
`

**Comment by 15dd** [comment]
别开梯子，把梯子关掉

**Comment by zxbiao** [comment]
> 别开梯子，把梯子关掉

没有开梯子，也一样崩

**Comment by 15dd** [comment]
登录界面有一个节点切换按钮，你切换成www.wenku8.net试试

**Comment by zxbiao** [comment]
> 登录界面有一个节点切换按钮，你切换成www.wenku8.net试试

用这个也一样崩
![Uploading Screenshot_20241002_145117.jpg…]()

**Comment by 15dd** [comment]
等一下，你的手机的系统语言设的是哪个

**Comment by zxbiao** [comment]
> 等一下，你的手机的系统语言设的是哪个

简体中文，但地区是中国香港

**Comment by 15dd** [comment]
你全调成简体中文再试一遍

**Comment by zxbiao** [comment]
> 你全调成简体中文再试一遍

全部设置成简体中文和中国大陆地区就能登陆了。
谢谢回复。

**Comment by 15dd** [comment]
你去软件的设置里手动设置为简体中文，然后就可以恢复之前的系统设置了，这是一个由自动跟随系统语言导致的bug

**Comment by zxbiao** [comment]
> 你去软件的设置里手动设置为简体中文，然后就可以恢复之前的系统设置了，这是一个由自动跟随系统语言导致的bug

在应用里设置了简体中文后，恢复手机原有的地区设置依旧会崩溃，但崩溃字体变简体中文了。

**Comment by 15dd** [comment]
崩溃的输出日志跟之前一样吗，这还能崩是我没有想到的

**Comment by zxbiao** [comment]
> 崩溃的输出日志跟之前一样吗，这还能崩是我没有想到的

没有留意崩溃日志，但点重启应用之后又能正常使用，不再崩溃了。

**Comment by 15dd** [comment]
那就这样吧

**Comment by zxbiao** [comment]
会不会是我需要翻墙回国的原因导致？两端的IP不一样导致wenku8输出了一些特殊返回信息之类的再导致崩溃。我在香港访问wenku8时会弹出CLOUDFLARE的3秒盾的。

**Comment by 15dd** [comment]
从你发的崩溃日志来看跟这个没什么关系
