### ISSUE TITLE
ver3.3.0的评论区bug

### ISSUE THREAD

**Issue by ShigureCN** [15dd/wenku8reader#43]
当在评论区同时打开两个评论时会崩溃
复现率100%

```
Build version: 3.3.0 
Build date: 1981-01-01 01:01:02 
Current date: 2024-12-06 14:10:35 
Device: OnePlus PJD110 
 
Stack trace:  
java.lang.NullPointerException
	at com.cyh128.hikari_novel.ui.view.detail.comment.reply.ReplyFragment$onViewCreated$2.invokeSuspend(ReplyFragment.kt:38)
	at com.cyh128.hikari_novel.ui.view.detail.comment.reply.ReplyFragment$onViewCreated$2.invoke(Unknown Source:13)
	at com.cyh128.hikari_novel.ui.view.detail.comment.reply.ReplyFragment$onViewCreated$2.invoke(Unknown Source:6)
	at com.cyh128.hikari_novel.ui.view.detail.comment.reply.ReplyFragment$onViewCreated$$inlined$receiveEvent$default$1.invokeSuspend(Channel.kt:75)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:221)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:177)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:149)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:591)
	at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(BufferedChannel.kt:2957)
	at kotlinx.coroutines.channels.BufferedChannelKt.access$tryResume0(BufferedChannel.kt:1)
	at kotlinx.coroutines.channels.BufferedChannel$BufferedChannelIterator.tryResumeHasNext(BufferedChannel.kt:1719)
	at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(BufferedChannel.kt:662)
	at kotlinx.coroutines.channels.BufferedChannel.updateCellSend(BufferedChannel.kt:478)
	at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(BufferedChannel.kt:33)
	at kotlinx.coroutines.channels.BufferedChannel.sendBroadcast$suspendImpl(BufferedChannel.kt:3450)
	at kotlinx.coroutines.channels.BufferedChannel.sendBroadcast$kotlinx_coroutines_core(Unknown Source:0)
	at kotlinx.coroutines.channels.BroadcastChannelImpl.send(BroadcastChannel.kt:179)
	at com.drake.channel.ChannelKt$sendEvent$1.invokeSuspend(Channel.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:282)
	at android.os.Looper.loop(Looper.java:387)
	at android.app.ActivityThread.main(ActivityThread.java:9501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1005)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d20a0df, Dispatchers.Main.immediate]
```

**Comment by 15dd** [comment]
同时打开两个回复？
一般一个评论区里只能打开一个回复啊，你怎么打开的两个回复，手太快了？

**Comment by 15dd** [comment]
已在3.3.1版本中修复
