### ISSUE TITLE
When open the software meet a bug

### ISSUE THREAD

**Issue by GoldBro233** [15dd/wenku8reader#45]
```
Build version: 3.3.2 
Build date: 1981-01-01 01:01:02 
Current date: 2024-12-24 15:45:17 
Device: Xiaomi M2102K1C 
 
Stack trace:  
java.lang.StringIndexOutOfBoundsException: begin 3, end -1, length 0
	at java.lang.String.checkBoundsBeginEnd(String.java:3942)
	at java.lang.String.substring(String.java:2467)
	at com.cyh128.hikari_novel.util.Wenku8Parser.getBookshelf(Wenku8Parser.kt:269)
	at com.cyh128.hikari_novel.data.repository.Wenku8Repository.getBookshelf-gIAlu-s(Wenku8Repository.kt:227)
	at com.cyh128.hikari_novel.data.repository.Wenku8Repository$getBookshelf$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4003879, Dispatchers.Main.immediate]
```
When I open the software I meet this bug, the log is upside, and I have tried to reboot but nothing worked.

**Comment by GoldBro233** [comment]
`Build version: 3.3.3 
Build date: 1981-01-01 01:01:02 
Current date: 2024-12-24 15:49:46 
Device: Xiaomi M2102K1C 
 
Stack trace:  
java.lang.StringIndexOutOfBoundsException: begin 3, end -1, length 0
	at java.lang.String.checkBoundsBeginEnd(String.java:3942)
	at java.lang.String.substring(String.java:2467)
	at com.cyh128.hikari_novel.util.Wenku8Parser.getBookshelf(Wenku8Parser.kt:269)
	at com.cyh128.hikari_novel.data.repository.Wenku8Repository.getBookshelf-gIAlu-s(Wenku8Repository.kt:227)
	at com.cyh128.hikari_novel.data.repository.Wenku8Repository$getBookshelf$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1d60140, Dispatchers.Main.immediate]
`
And it appears when I update to the latest version.

**Comment by 15dd** [comment]
1、为什么你用英文，你是外国人？
2、这个报错是因为你网络环境的问题，你用中国的ip试试

**Comment by 15dd** [comment]
没有加代理，而且一般来说除了部分ip属地外，都能直连wenku8
